site_name: Image Finder Docs
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true 

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - Dataset: dataset.md
  - Frontend:
      - Overview: frontend/overview.md
      - Setup: frontend/setup.md
  - Backend:
      - Overview: backend/overview.md
      - API: backend/api.md
  - Notebooks:
      - Initial Table Generation: notebooks/initial-table.ipynb      

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - js/math.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css


repo_url: https://github.com/denkmoritz/image_finder
